# Default values for jet-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

imageCredentials:
  registry: registry.cn-hangzhou.aliyuncs.com
  username: deploy-man@skylark
  password: changeit
  email: dev@byzan.team

airbase:
  image:
    repository: jet/airbase_umbrella
    tag: "release"
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

# [Jet]
jetSubpath: /
jetHost: jet.localhost
jetTLSSecret:

# [Airbase]
airbaseDeploymentID:
airbaseLocaleDomain: default
airbaseLoggerLevel: info

airbaseOSSPrivateBucket: minio-private
airbaseOSSPublicBucket: minio-public

airbaseStorageDatabaseFileFieldFilesizeMax: 10485760
airbaseStorageDatabaseTransportationImportationSourceFilesizeMax: 10485760
airbaseStorageDatabaseTransportationImportationFailureFilesizeMax: 10485760
airbaseStorageSandboxProgramFilesizeMax: 10485760

airbaseAlixirSMSAccessKeyID: abc
airbaseAlixirSMSAccessSecret: overwriteit
airbaseAlixirSMSAccessVerificationCodeSignName: 了了科技
airbaseAlixirSMSAccessVerificationCodeTemplateCode: changeti

airbaseSentryDsn: ""
airbaseSentryRelease: beta

airbaseJokenSigner: "$ecrEt"

airbaseWechatAppID: ""
airbaseWechatSecret: ""
airbaseWechatAuditCode: ""
airbasewechatAuditPhone: ""

airbaseCacheConcurrencyLimit: 10
airbaseCacheBufferSize: 1

airbaseOpsLiveDashboardUsername: ""
airbaseOpsLiveDashboardPassword: ""

# for app installation
airbaseVolumesHostPath:

# [PostgreSQL]
postgresqlUser: postgres
postgresqlPassword: postgres
postgresqlIP: 10.0.0.18
postgresqlPort: 5432
postgresqlAirbaseDatabase: airbase_prod
postgresqlAirbasePoolSize: 30
postgresqlEventStoreDatabase: eventstore_prod
postgresqlEventStorePoolSize: 60

# [Minio]
minioRootUser: minioadmin
minioRootPassword: minioadmin
minioScheme: http://
minioHost: oss.jet.localhost
minioTLSSecret:
minioPort: 80
minioServiceIP: 10.0.0.18
minioServicePort: 9000
