apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.airbaseServerName }}`) && Path(`/api`, `/subscriptions`, `/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
    - match: Host(`{{ .Values.airbaseServerName }}`) && Path(`/app_store/api`, `/app_store/explorer`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
    - match: Host(`{{ .Values.airbaseServerName }}`) && PathPrefix(`/oss/`)
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" . }}-airbase
          port: 80
