{{- $rules := list }}
{{- $rules = append $rules (printf "Host(`%s`) && PathPrefix(`/%s`)" .Values.minioHost .Values.airbaseOSSPrivateBucket) }}
{{- $rules = append $rules (printf "Host(`%s`) && PathPrefix(`/%s`)" .Values.minioHost .Values.airbaseOSSPublicBucket) }}

{{/* Middlewares for web ingress-routes */}}
{{- $webMiddlewares := list }}
{{- $webMiddlewares = append $webMiddlewares "compress" }}
{{- if .Values.minioTLSSecret | empty | not }}
{{- $webMiddlewares = append $webMiddlewares "redirect-to-https" }}
{{- end }}

{{/* Middlewares for websecure ingress-routes */}}
{{- $websecureMiddlewares := list }}
{{- $websecureMiddlewares = append $websecureMiddlewares "compress" }}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio
spec:
  entryPoints:
    - web
  routes:
    {{- range $rules }}
    - match: {{ . }}
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" $ }}-minio
          port: 9000
      middlewares:
        {{- range $webMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}

---

{{- if .Values.minioTLSSecret | empty | not }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "jet-chart.fullname" . }}-minio-websecure
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $rules }}
    - match: {{ . }}
      kind: Rule
      services:
        - name: {{ include "jet-chart.fullname" $ }}-minio
          port: 9000
      middlewares:
        {{- range $websecureMiddlewares }}
        - name: {{ include "jet-chart.fullname" $ }}-{{ . }}
        {{- end}}
    {{- end }}
  tls:
    secretName: {{ include "jet-chart.fullname" $ }}-mimio-tls-secret
{{- end }}
