apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
data:
  TZ: Asia/Shanghai
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL: en_US.UTF-8

  MIX_ENV: prod
  ENABLE_SSL: {{ .Values.jetTLSSecret | empty | not | quote }}
  JET_SERVER_NAME: {{ .Values.jetHost }}
  PORT: "4000"
  LOCALE_DOMAIN: {{ .Values.airbaseLocaleDomain }}
  JET_DEPLOYMENT_ID: {{ .Values.airbaseDeploymentID | default (.Release.Name) }}
  MIX_LOGGER_LEVEL: {{ .Values.airbaseLoggerLevel }}

  JET_OSS_PRIVATE_BUCKET: {{ .Values.airbaseOSSPrivateBucket }}
  JET_OSS_PUBLIC_BUCKET: {{ .Values.airbaseOSSPublicBucket }}

  JET_STORAGE_DATABASE_FILE_FIELD_FILESIZE_MAX: {{ .Values.airbaseStorageDatabaseFileFieldFilesizeMax | int | quote }}
  JET_STORAGE_DATABASE_TRANSPORTATION_IMPORTATION_SOURCE_FILESIZE_MAX: {{ .Values.airbaseStorageDatabaseTransportationImportationSourceFilesizeMax | int | quote }}
  JET_STORAGE_DATABASE_TRANSPORTATION_IMPORTATION_FAILURE_FILESIZE_MAX: {{ .Values.airbaseStorageDatabaseTransportationImportationFailureFilesizeMax | int | quote }}
  JET_STORAGE_SANDBOX_PROGRAM_FILESIZE_MAX: {{ .Values.airbaseStorageSandboxProgramFilesizeMax | int | quote }}

  JET_ALIXIR_SMS_ACCESS_KEY_ID: {{ .Values.airbaseAlixirSMSAccessKeyID }}
  JET_ALIXIR_SMS_ACCESS_SECRET: {{ .Values.airbaseAlixirSMSAccessSecret }}
  JET_ALIXIR_SMS_ACCESS_VERIFICATION_CODE_SIGN_NAME: {{ .Values.airbaseAlixirSMSAccessVerificationCodeSignName }}
  JET_ALIXIR_SMS_ACCESS_VERIFICATION_CODE_TEMPLATE_CODE: {{ .Values.airbaseAlixirSMSAccessVerificationCodeTemplateCode }}

  JET_SENTRY_DSN: {{ .Values.airbaseSentryDsn | quote }}
  JET_RELEASE: {{ .Values.airbaseSentryRelease | quote }}

  JET_JOKEN_SIGNER: {{ .Values.airbaseJokenSigner | quote }}

  WECHAT_APP_ID: {{ .Values.airbaseWechatAppID | quote }}
  WECHAT_SECRET: {{ .Values.airbaseWechatSecret | quote }}
  WECHAT_AUDIT_PHONE: {{ .Values.airbasewechatAuditPhone | quote }}
  WECHAT_AUDIT_CODE: {{ .Values.airbaseWechatAuditCode | quote }}

  JET_AIRBASE_CACHE_CONCURRENCY_LIMIT: {{ .Values.airbaseCacheConcurrencyLimit | quote }}
  JET_AIRBASE_CACHE_BUFFER_SIZE: {{ .Values.airbaseCacheBufferSize | quote }}

  OPS_LIVE_DASHBOARD_USERNAME: {{ .Values.airbaseOpsLiveDashboardUsername | quote }}
  OPS_LIVE_DASHBOARD_PASSWORD: {{ .Values.airbaseOpsLiveDashboardPassword | quote }}
