{{- $volumesHostPath := .Values.airbaseVolumesHostPath -}}

{{- if $volumesHostPath | empty | not -}}
{{- if $volumesHostPath | isAbs | not -}}
{{- fail "Expect the `.Values.airbaseVolumesHostPath` an absolute path, or unset to disable it" -}}
{{- end -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jet-chart.fullname" . }}-airbase
  labels:
    {{- include "jet-chart.labels" . | nindent 4 }}
    app: {{ include "jet-chart.fullname" . }}-airbase
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jet-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jet-chart.selectorLabels" . | nindent 8 }}
        app: {{ template "jet-chart.fullname" . }}-airbase
    spec:
      imagePullSecrets:
        - name: {{ include "jet-chart.fullname" . }}-docker-registry-secret
      containers:
        - name: {{ .Chart.Name }}-airbase
          image: {{ include "jet-chart.airbase-image" . }}
          imagePullPolicy: {{ .Values.airbase.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-postgresql
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-minio
            - configMapRef:
                name: {{ include "jet-chart.fullname" . }}-airbase
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            {{- toYaml .Values.airbase.resources | nindent 12 }}

          volumeMounts:
          {{- if $volumesHostPath | empty | not }}
            - name: airbase-apps-storage
              mountPath: /data
          {{- end }}
          {{ - if .Values.postgresqlSsl.enabled }}
            - name: airbase-db-ca-cert
              mountPath: /app/cert
              readOnly: true
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      {{- if $volumesHostPath | empty | not }}
        - name: airbase-apps-storage
          hostPath:
            path: {{ $volumesHostPath }}
            type: DirectoryOrCreate
      {{- end -}}
      {{ - if .Values.postgresqlSsl.enabled }}
        - name: airbase-db-ca-cert
          secret:
            secretName: {{ .Values.postgresqlSsl.caSecretName }}
      {{- end }}
